### ISSUE TITLE
Roadmap to 3.0.0

### ISSUE THREAD

**Issue by cMadan** [cMadan/prism#3]
Prism is good so far, but there are some additional features needed for on-going projects that I need to add in.

## Already exist in development versions
- [x] Add feature for initial z-scoring of data before spline step
- [x] Output BIC as additional measure of model fitness (also still R2)

## More involved
- [ ] new function [`prism_relevance`] - back-project from RVR to PCA--determine weights for individual predictors from original data columns

## Minor
- [x] Begin development
- [x] Add JOSS doi badge
- [ ] Revise readme me new features
- [ ] Re-run benchmarks

## Final
- [ ] Push 3.0.0 release
